@startuml
participant "Dapp\n(NebPay)" as NebPay
participant "Wallet App" as App
participant Server as server
participant "Nebulas\nBlockChain" as chain

NebPay -> App: serialNumber = nebpay.pay( )
App -> chain: send transaction
App <- chain: return TxHash
App -> server: save (serialNumber, TxHash) to server
...
|||
NebPay --> server: queryPayInfo(serialNumber,options)
server --> chain:  get tx receipt by TxHash
server <-- chain: return tx receipt data
NebPay <-- server: \t\t\t\t\t\t\t return PayInfo
@enduml 